#!/bin/sh /etc/rc.common

START=19

OPENWIFI_DIR=/root/openwifi

boot() {
	logger -t openwifi "OPENWIFI SERVICE BOOT"

	logger -t openwifi "Loading kernel modules"
	cd $OPENWIFI_DIR
	sh wgd.sh

	logger -t openwifi "OPENWIFI DONE LOADING"
}
